### PR TITLE
Create UpdateDependabotPR.yml

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by niklassiemer** [comment]
I just finished the new version which allows for other package names in setup and environment. However, I do not know if you actually need it here.
Otherwise, it looks good to me.

**Comment by jan-janssen** [comment]
> I just finished the new version which allows for other package names in setup and environment. However, I do not know if you actually need it here.
> Otherwise, it looks good to me.

I guess the easiest way would be to move the script to a separate repository, then we can update it centrally rather than updating each repository/

**Comment by niklassiemer** [comment]
Right now, I wonder how to do it best.... With the diversity of our packages I do not think we could replace the whole `.github` folder, nor the `.ci_support` one. We could add a `.dependabot_support` folder pointing to such a submodule with a name conversion script?

**Comment by jan-janssen** [comment]
In particular - talking about it - I am not sure if we can actually move the .github folder to a separate repository - not sure if the CI still works afterwards.

**Pull request merged**
