### PR TITLE
Use `oversubscribe` option only for Dask clusters

### PR DESCRIPTION
**Pull request by srmnitc**
The MPI run command uses `oversubscribe` option which is only useful if Dask clusters are used. However, this option fails with mpich. I added a small workaround, which only uses this option if a Dask cluster is used.

This fix could be the solution for [this](https://github.com/pyiron/pyiron_atomistics/issues/484) and [this](https://github.com/pyiron/pyiron_atomistics/issues/377).

@niklassiemer Could you please help with the tag for black formatting?

### CODE REVIEW

**Comment by niklassiemer** [comment]
Sure, I completely forgot to push that tag and workflow to all repos.

**Comment by jan-janssen** [comment]
> The MPI run command uses `oversubscribe` option which is only useful if Dask clusters are used. However, this option fails with mpich. I added a small workaround, which only uses this option if a Dask cluster is used.

To my knowledge the whole trick of communicating via stdin and stdout only works with OpenMPI but not mpich. At least for large structures - that is why I did not care about mpich support so far.

**Comment by srmnitc** [comment]
I was not aware of this; then there is really need for this change. I will run a few more tests before we go ahead and close it.

**Comment by jan-janssen** [comment]
> I was not aware of this; then there is really need for this change. I will run a few more tests before we go ahead and close it.

As I see no progress on this pull request I close it now. Feel free to re-open it.

**Pull request closed without merging**
