### PR TITLE
Fix create_atoms()

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by jan-janssen** [comment]
In some way this is reverting https://github.com/pyiron/pylammpsmpi/pull/29

**Comment by jan-janssen** [comment]
@srmnitc Can you take a look at these changes? I just want to make sure they do not interrupt the functionality you use in `calphy`.

**Comment by srmnitc** [comment]
Sure, I will test it today.

**Comment by srmnitc** [comment]
@jan-janssen Some changes were needed on the calphy side, but these are done in the new release. Everything works now. Feel free  to merge this in. Thanks!

**Comment by jan-janssen** [comment]
> @jan-janssen Some changes were needed on the calphy side, but these are done in the new release. Everything works now. Feel free to merge this in. Thanks!

Can you link the corresponding pull request? I am just wondering if you use the lammps commands as python functions, because that is something I never used.

**Pull request merged**
