### PR TITLE
Create .coveralls.yml

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by jan-janssen** [comment]
Somehow four tests started to fail: 
```
======================================================================
11
FAIL: test_gather_atoms (test_pylammpsmpi_cluster.TestLocalLammpsLibrary)
12
----------------------------------------------------------------------
13
Traceback (most recent call last):
14
  File "/home/runner/work/pylammpsmpi/pylammpsmpi/tests/test_pylammpsmpi_cluster.py", line 38, in test_gather_atoms
15
    self.assertEqual(np.round(f[-22][0], 2), 0.31)
16
AssertionError: 0.0 != 0.31
17

18
======================================================================
19
FAIL: test_scatter_atoms (test_pylammpsmpi_cluster.TestLocalLammpsLibrary)
20
----------------------------------------------------------------------
21
Traceback (most recent call last):
22
  File "/home/runner/work/pylammpsmpi/pylammpsmpi/tests/test_pylammpsmpi_cluster.py", line 73, in test_scatter_atoms
23
    self.assertEqual(f1[1][0], val)
24
AssertionError: 0.0 != 28
25

26
======================================================================
27
FAIL: test_gather_atoms (test_pylammpsmpi_local.TestLocalLammpsLibrary)
28
----------------------------------------------------------------------
29
Traceback (most recent call last):
30
  File "/home/runner/work/pylammpsmpi/pylammpsmpi/tests/test_pylammpsmpi_local.py", line 35, in test_gather_atoms
31
    self.assertEqual(np.round(f[-22][0], 2), 0.31)
32
AssertionError: 0.0 != 0.31
33

34
======================================================================
35
FAIL: test_scatter_atoms (test_pylammpsmpi_local.TestLocalLammpsLibrary)
36
----------------------------------------------------------------------
37
Traceback (most recent call last):
38
  File "/home/runner/work/pylammpsmpi/pylammpsmpi/tests/test_pylammpsmpi_local.py", line 71, in test_scatter_atoms
39
    self.assertEqual(f1[1][0], val)
40
AssertionError: 0.0 != 44
41

42
----------------------------------------------------------------------
43
Ran 12 tests in 1.393s
```

**Comment by jan-janssen** [comment]
As both the local and the cluster version fails I have the feeling the LAMMPS API was changed @srmnitc any idea?

**Comment by srmnitc** [comment]
Seems like it might have changed. The [docs](https://lammps.sandia.gov/doc/Python_module.html) look updated.

**Comment by jan-janssen** [comment]
It seems like this bug was fixed in the late november release https://github.com/lammps/lammps/releases/tag/patch_30Nov2020 
So I am going to try to release a new conda version: 
https://github.com/conda-forge/lammps-feedstock/pull/52

**Pull request merged**
