### PR TITLE
Switch from pytest to unittest

### PR DESCRIPTION
**Pull request by jan-janssen**

### CODE REVIEW

**Comment by jan-janssen** [comment]
[Coverage Status](https://coveralls.io/github/pyiron/pylammpsmpi)

**Review by srmnitc — APPROVED** [review]
Looks good. Out of curiosity, is there a specific reason to move to unittest?

**Comment by jan-janssen** [comment]
It is mainly my personal preference. At some point we decided to use unit tests for the pyiron project as it is a bit more clean and nicely integrates with tools like pycharm. But it is really just a suggestion. If you have a strong preference for pytest we can also stay with pytest.

**Comment by srmnitc** [comment]
No not at all, I was just curious. No problems at all switching to unittest

**Pull request merged**
